#!/bin/sh

# This hook is invoked by git-merge, which happens when a git pull is done on a local repository.
if [[ "$OSTYPE" == "msys" ]]; then
    echo "Windows"
    # TODO
    # ./generate_project.bat
    # call vendor\premake5\premake5.exe vs2022
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    echo "Linux"
    # TODO
    # ./generate_project.sh
    # vendor/premake5/premake5 gmake2
else
    echo "post-merge GIT Hook Error: The operating system is not supported"
fi
