#!/bin/sh

# This hook is invoked by git-merge, which happens when a git pull is done on a local repository.
if [[ "$OSTYPE" == "msys" ]]; then
    echo "Windows"
    # TODO
    # ./generate_project.bat
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    echo "Linux"
    # TODO
    # ./generate_project.sh
else
    echo "post-merge GIT Hook Error: The operating system is not supported"
fi
