name: Build Windows

on:
  workflow_call:

env:
  PROJECT_NAME: 'ParticleSystem'
  SOLUTION_FILE_PATH: 'ParticleSystem.sln'
  ZIP_NAME: 'windows-x64'

jobs:
  windows:
    runs-on: windows-latest
    
    strategy:
      fail-fast: false
      matrix:
        build-configuration: [Debug, Release]
        build-platform: [x64]
    
    steps:
    - name: Clone Git Repository
      uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64
    
    - name: Setup
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: cmd /c "generate_project.bat"
    
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: MSBuild ${{env.SOLUTION_FILE_PATH}} /m /p:Configuration=${{matrix.build-configuration}} /p:Platform=${{matrix.build-platform}}

    - name: Move artifacts to Release Folder
      if: startsWith(github.ref, 'refs/tags/') && matrix.build-configuration == 'Release'
      run: |
        mkdir ${{ env.ZIP_NAME }}
        copy bin/Release-windows-x86_64/${{ env.ZIP_NAME }}/*.exe ${{ env.ZIP_NAME }}
        copy bin/Release-windows-x86_64/${{ env.ZIP_NAME }}/*.dll ${{ env.ZIP_NAME }}

        mkdir -p "${{ env.ZIP_NAME }}\resources"
        xcopy ${{ env.ZIP_NAME }}\resources "${{ env.ZIP_NAME }}\resources" /E /H

        mkdir -p "${{ env.ZIP_NAME }}\shaders"
        xcopy ${{ env.ZIP_NAME }}\shaders "${{ env.ZIP_NAME }}\shaders" /E /H

        dir /a ${{ env.ZIP_NAME }}
    
    - name: Set Tag Name
      if: startsWith(github.ref, 'refs/tags/') && matrix.build-configuration == 'Release'
      shell: bash
      run: echo "TAG_NAME=${GITHUB_REF#'refs/tags/'}" >> ${GITHUB_ENV}
    
    - name: Add tag to folder name
      if: startsWith(github.ref, 'refs/tags/') && matrix.build-configuration == 'Release'
      run: move ${{ env.ZIP_NAME }} ${{ env.ZIP_NAME }}-${{ env.TAG_NAME }}
    
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      if: startsWith(github.ref, 'refs/tags/') && matrix.build-configuration == 'Release'
      with:
        type: 'zip'
        path: ${{ env.ZIP_NAME }}-${{ env.TAG_NAME }}
        filename: ${{ env.ZIP_NAME }}-${{ env.TAG_NAME }}.zip
    
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/') && matrix.build-configuration == 'Release'
      with:
        files: ${{ env.ZIP_NAME }}-${{ env.TAG_NAME }}.zip
